export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  PRODUCER_VIEW: 'producer.view',
  PRODUCER_CREATE: 'producer.create',
  PRODUCER_UPDATE: 'producer.update',
  PRODUCER_DELETE: 'producer.delete',
  NURSERY_VIEW: 'nursery.view',
  NURSERY_CREATE: 'nursery.create',
  NURSERY_UPDATE: 'nursery.update',
  NURSERY_DELETE: 'nursery.delete',
  SEED_GARDEN_VIEW: 'seed-garden.view',
  SEED_GARDEN_CREATE: 'seed-garden.create',
  SEED_GARDEN_UPDATE: 'seed-garden.update',
  SEED_GARDEN_DELETE: 'seed-garden.delete',
  PRODUCTION_VIEW: 'production.view',
  PRODUCTION_CREATE: 'production.create',
  PRODUCTION_UPDATE: 'production.update',
  PRODUCTION_DELETE: 'production.delete',
  APPLICATION_VIEW: 'application.view',
  APPLICATION_CREATE: 'application.create',
  APPLICATION_VERIFY: 'application.verify',
  APPLICATION_ASSIGN: 'application.assign',
  INSPECTION_VIEW: 'inspection.view',
  INSPECTION_EXECUTE: 'inspection.execute',
  INSPECTION_FINALIZE: 'inspection.finalize',
  CERTIFICATE_VIEW: 'certificate.view',
  CERTIFICATE_UPLOAD: 'certificate.upload',
  CERTIFICATE_VERIFY: 'certificate.verify',
  CERTIFICATE_REPLACE: 'certificate.replace',
  REPORT_VIEW: 'report.view',
  REPORT_EXPORT: 'report.export',
  USER_MANAGE: 'user.manage',
  ROLE_MANAGE: 'role.manage',
  AUDIT_VIEW: 'audit.view',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
