import { ALL_PERMISSIONS, PERMISSIONS } from './permissions';
import { ROLES } from './roles';

/** Sumber tunggal permission per role (5 role) */
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,

  /** Monitoring & laporan — tanpa penugasan/upload scan */
  [ROLES.PIMPINAN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCER_VIEW,
    PERMISSIONS.NURSERY_VIEW,
    PERMISSIONS.SEED_GARDEN_VIEW,
    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.CERTIFICATE_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
  ],

  /** Operasional penuh sertifikasi */
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCER_VIEW,
    PERMISSIONS.PRODUCER_CREATE,
    PERMISSIONS.PRODUCER_UPDATE,
    PERMISSIONS.PRODUCER_DELETE,
    PERMISSIONS.NURSERY_VIEW,
    PERMISSIONS.NURSERY_CREATE,
    PERMISSIONS.NURSERY_UPDATE,
    PERMISSIONS.NURSERY_DELETE,
    PERMISSIONS.SEED_GARDEN_VIEW,
    PERMISSIONS.SEED_GARDEN_CREATE,
    PERMISSIONS.SEED_GARDEN_UPDATE,
    PERMISSIONS.SEED_GARDEN_DELETE,
    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.PRODUCTION_CREATE,
    PERMISSIONS.PRODUCTION_UPDATE,
    PERMISSIONS.PRODUCTION_DELETE,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_CREATE,
    PERMISSIONS.APPLICATION_VERIFY,
    PERMISSIONS.APPLICATION_ASSIGN,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INSPECTION_EXECUTE,
    PERMISSIONS.INSPECTION_FINALIZE,
    PERMISSIONS.CERTIFICATE_VIEW,
    PERMISSIONS.CERTIFICATE_UPLOAD,
    PERMISSIONS.CERTIFICATE_VERIFY,
    PERMISSIONS.CERTIFICATE_REPLACE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
  ],

  /** Lapangan: tugas & pemeriksaan sendiri */
  [ROLES.PBT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCER_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.INSPECTION_EXECUTE,
    PERMISSIONS.INSPECTION_FINALIZE,
    PERMISSIONS.CERTIFICATE_VIEW,
  ],

  /** Eksternal: data & pengajuan milik sendiri */
  [ROLES.PENANGKAR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.NURSERY_VIEW,
    PERMISSIONS.PRODUCTION_VIEW,
    PERMISSIONS.PRODUCTION_CREATE,
    PERMISSIONS.PRODUCTION_UPDATE,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_CREATE,
    PERMISSIONS.INSPECTION_VIEW,
    PERMISSIONS.CERTIFICATE_VIEW,
  ],
};
